services:
  base: &base-spec
    build: .
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  ubuntu24.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:24.04

  ubuntu22.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:22.04

  ubuntu20.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:20.04

  arch:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile.arch
