name: Lint
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!*.md'

  pull_request:
    paths:
      - '**'
      - '!*.md'

  schedule:
    - cron: '0 1 * * *'

jobs:
  lint:
    name: Lint
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        nix develop -c uv sync --group dev

    - name: Run linters
      run: |
        nix develop -c ./lint.sh
